server:
  port: 20226
#spring:
#  shardingsphere:
#    datasource:
#      names: ds_0, ds_1
#      ds_0:
#        type: com.zaxxer.hikari.HikariDataSource
#        driverClassName: com.mysql.cj.jdbc.Driver
#        jdbcUrl: jdbc:mysql://localhost:3306/demo_ds_0?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
#        username: root
#        password: 123456
#      ds_1:
#        type: com.zaxxer.hikari.HikariDataSource
#        driverClassName: com.mysql.cj.jdbc.Driver
#        jdbcUrl: jdbc:mysql://localhost:3306/demo_ds_1?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
#        username: root
#        password: 123456
#    rules:
#        dataSources:
#          dataSources1:
#            type: Dynamic
#            props:
##              auto-aware-data-source-name: demo_ds_0
#              write-data-source-name: ds_0
#              read-data-source-names: ds_1
#            loadBalancerName: loadBalancers1
#        loadBalancers:
#          loadBalancers1:
#            type: RANDOM

spring:
  datasource:
    first:
      type: com.zaxxer.hikari.HikariDataSource
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/demo_ds_0?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 123456
    second:
      type: com.zaxxer.hikari.HikariDataSource
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/demo_ds_1?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 123456
